import { ClerkProvider } from '@clerk/nextjs'
import type { Metadata } from 'next'
import { Toaster } from 'sonner'
import '../styles/globals.css'

import { geistMono, geistSans } from '@/styles/fonts'

export const metadata: Metadata = {
	title: 'Healthcare System',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<ClerkProvider afterSignOutUrl={'/'}>
			<html lang="en">
				<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
					{children}
					<Toaster
						position="top-center"
						richColors
					/>
				</body>
			</html>
		</ClerkProvider>
	)
}
